spring:
  jackson:
    time-zone: Asia/Seoul
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  cloud:
    aws:
      s3:
        bucket: stackpot
        path:
          FeedFile: FeedFile
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
  jwt:
    secret: ${JWT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  task:
    scheduling:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379